### ISSUE TITLE
component?

### ISSUE THREAD

**Issue by bagvand** [behnejad/gosling#2]
آیا ما کامپوننت هایی با نام های زیر نداریم
GroupList
Group
Examlist
exam
?
اگه داریم آیا نیازی هست هر کدوم یه 
app
داخل جنگو باشن؟
یا اینکه اینی که الان هست خوبه
در حال حاظر همه جزو 
exam 
هستند!

امید و هومن بیافتید به جون هم!
بحث کنید!
:دی

**Comment by omiddavoodi** [comment]
داریم. هنوز ایجاد نشدن ولی قراره داشته باشیم. شب بخیر.
